### ISSUE TITLE
Write a function upload history into mongoDB

### ISSUE THREAD

**Issue by ypling** [CCCBTICC/ROIServer#10]
- load data into mongoDB form R/import folder.
- Into history collection.
- run each time when we start the server.
- clean old data
- function define in serverUtility module

**Comment by yzrzya1** [comment]
implemented 3 functions :   (in  api/modules/Importmodule.js)
deleteCollection ---1> drop original collection by pass collection Name as parameter.
importCollection ---2> import json file from api/import/[collectionName].json to mongo DB  
exportCollection ---3> export json file from mongo DB   to api/import/[collectionName].json

if you guys need any combine these three functions please tell me

**Comment by yzrzya1** [comment]
this problem is solved  and I updated in Albert branch if any questions plz ask me .

**Comment by ypling** [comment]
Could you please integrate this functions into server base on our needs:
1. run each time when we start the server.
2.clean old data.
3.function define in serverUtility module.
4.load data into mongoDB form R/import folder.

**Comment by ypling** [comment]
reviewed
