### ISSUE TITLE
Scenario list should always show table header and operation buttons

### ISSUE THREAD

**Issue by ypling** [CCCBTICC/ROIServer#11]
When screen is big enough.

**Comment by lhz213** [comment]
4 files were changed.
- home.html
  - remove `<footer></footer>` tag
- main.css
  - change classes about table
  - add `.thead-fixed-top` class. Using with `<table></table>` tag: `<table class="thead-fixed-top"></table>`, and also a piece of inline javascript code above the table in scenario. I wrote it using jQuery. 
  - add `.controls` class, All the buttons under tables or blocks can apply these class to make the button in the center of the page.
- change myscenarios/list.html
  - change the `table` styles.
- roi.directiveModule.js
  - add filter `TLNR` for the context too long in table-cell. Default is 1 column  and 1 row. 
    `{{ ngModelText | TLNR:[numberOfCol]:[numberOfRow] }}`. TLNR means too long, no read..

**Comment by yzrzya1** [comment]
Here is a good example to solve it. 
http://jaimonblog.appspot.com/datascroller/fixedHeaderFullClone.html

**Comment by yzrzya1** [comment]
you already did it.   great job
