### ISSUE TITLE
Welcome Message

### ISSUE THREAD

**Issue by sanjoyhaldar** [CCCBTICC/ROIServer#13]
![user-info](https://cloud.githubusercontent.com/assets/13476703/8883056/e10f4ec0-3200-11e5-815a-1d9e9cb5cc95.JPG)
1. Make the first letter of the user name Uppercase
2. Format the Last Logged date as MMM DD, YYYY

**Comment by lhz213** [comment]
1. 

``` javascript
app.filter('name', function() {
  return function(input, scope) {
    if (input!=null)
    input = input.toLowerCase();
    return input.substring(0,1).toUpperCase()+input.substring(1);
  }
});
```

``` html
Welcome, <strong>{{users.name | name}}</strong>
```

2.

``` html
<strong>{{users.recentlyLoginDate | date: 'MMM dd yyyy'}}</strong>
```

I think this should be fine for this issue.

**Comment by yzrzya1** [comment]
don't forget the  comma between login Date

**Comment by lhz213** [comment]
In branch #11

**Comment by canvas103** [comment]
name filter and date format are updated
