### ISSUE TITLE
clear up API

### ISSUE THREAD

**Issue by ypling** [CCCBTICC/ROIServer#2]
Clean up API
- PlanInitOutput
- PlanRunOutput

**Comment by ypling** [comment]
I move scenarios api into api folder.
@yzrzya1 could you please implement scenario APIs here?
Use postman to test your API then modify mockapi/scenarios base on response data.
You can switch between mockapi and api by change the apiFolderName in server.js
Any question please let me know.

**Comment by ypling** [comment]
BTW Let's just use GET and POST method
and different POST request should detect by req.body.action

**Comment by Zacharysp** [comment]
Ha, what's this project for, from your work?

On Thursday, July 16, 2015, Leonard Li <notifications@github.com> wrote:

> BTW Let's just use GET and POST method
> and different POST request should detect by req.body.action
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CCCBTICC/ROIServer/issues/2#issuecomment-122198579>.
>


-- 
Dongjie Zhang

Email: sp151018@gmail.com

Cell: 510-386-9778

**Comment by ypling** [comment]
Just a project from a CCC named FocusKpi.
Trying to help them.

**Comment by Zacharysp** [comment]
Wow, u r nice. How's the work going?

On Friday, July 17, 2015, Leonard Li <notifications@github.com> wrote:

> Just a project from a CCC named FocusKpi.
> Trying to help them.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CCCBTICC/ROIServer/issues/2#issuecomment-122202803>.
>


-- 
Dongjie Zhang

Email: sp151018@gmail.com

Cell: 510-386-9778

**Comment by ypling** [comment]
yeah I'm doing well. Thank. How about yours?

**Comment by Zacharysp** [comment]
It's getting busy lately, I have to delivery something due to the end of
this month. Did u move to San Jose?

On Friday, July 17, 2015, Leonard Li <notifications@github.com> wrote:

> yeah I'm doing well. Thank. How about yours?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CCCBTICC/ROIServer/issues/2#issuecomment-122204874>.
>


-- 
Dongjie Zhang

Email: sp151018@gmail.com

Cell: 510-386-9778

**Comment by ypling** [comment]
cleaned up in branch ISSUE-2
