### ISSUE TITLE
Look back using history data

### ISSUE THREAD

**Issue by ypling** [CCCBTICC/ROIServer#28]

**Comment by ypling** [comment]
Pleas, create look back api that
receives startDate and endDate
returns calculated history Data

**Comment by yzrzya1** [comment]
already implement it and tested on post man.

some example test case: 
1. send post -> http://localhost:3001/analysis/lookback  ->  raw (JSON) 

result:
[
  {
    "_id": "55a97a43977efefdb147e25f",
    "": 46,
    "Affiliate": 80244,
    "Affiliates_LTA": 1224932,
    "Affiliates_MTA": 629772,
    "DM": 384897,
    "Display": 425398,
    "Display_LTA": 2257171,
    "Display_MTA": 1815659,
    "FB": 150389,
    "FB_LTA": 691207,
    "FB_MTA": 402876,
    "Month": "2015-01",
    "Partners": 1118944,
    "Partners_LTA": 3418714,
    "Partners_MTA": 5989201,
    "Revenue": 40309494,
    "SEM": 898576,
    "SEMBrand": 205190,
    "SEMCard": 349518,
    "SEMOther": 165386,
    "SEMPBook": 178480,
    "SEM_LTA": 7501474,
    "SEM_MTA": 6597105,
    "TV": 0,
    "TVImpression": 0
  }
]
1.  get  -> http://localhost:3001/analysis/lookback 

result :

{
  "earliest": "2011-04",
  "latest": "2015-05"
}
